######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 1 15:53:48 2015
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QMAKE_CXXFLAGS = -std=c++11
OBJECTS_DIR = .obj
